### ISSUE TITLE
R code not working

### ISSUE THREAD

**Issue by victorhartman** [DHSProgram/DHS-Indicators-R#1]
The code seems to be incompatible with the dataset itself. 

For example looking at https://github.com/DHSProgram/DHS-Indicators-R/blob/main/Chap02_PH/PH_POP.R#L44 

Selection a column using PRdata[["hv103"]] would not work as that column does not exist! Instead there are multiple hv103 columsn, going hv103_01, hv103_02, hv103_03 etc.

I would really like to get this code running and to reproduce some of the figures in the report. Any help is appreciated.

**Comment by shireen122** [comment]
Dear Victor,

Thank you for your question.

It appears you are using the HR file not the PR file. The HR file is the household level data and contains the variables hv103_01, hv103_02, etc. to indicate each person living in the household (i.e. here the unit of analysis is the household). 
The PR file is person recode file with data on each member of the household so the variable would be hv105. Here the unit of analysis is the individual in the household. 

Please check that you are using the PR file and not the HR file.

Thank you.

**Comment by victorhartman** [comment]
Hi Shireen,

Thank you for looking into to this. You are indeed right, I was apparently working with the incorrect files.

Thanks!
